version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jfree:jfreechart
    versions:
    - ">= 1.5.a"
    - "< 1.6"
  - dependency-name: org.kordamp.ikonli:ikonli-materialdesign-pack
    versions:
    - ">= 11.a"
    - "< 12"
  - dependency-name: org.kordamp.ikonli:ikonli-swing
    versions:
    - ">= 11.a"
    - "< 12"
  - dependency-name: org.netbeans.api:org-openide-util-lookup
    versions:
    - "> RELEASE82"
